In [23]:
import numpy as np

file = np.load('./data/test_filter_sampling/filters.npy', mmap_mode='r')

print(np.shape(file))
print(file)

def chirp_mass(m1, m2):
    return ((m1 * m2)**0.6)/ (m1 + m2)**0.2

for i in file:
    print(chirp_mass(i[1][0], i[1][1]))

(11, 2, 4)
[[[ 1.0582612e+02  3.0375451e+00  8.8487153e-01 -5.5820806e-01]
  [ 1.1660774e+02  2.8585063e+00  9.9779461e-01 -7.0717296e-01]]

 [[ 1.8898542e+02  2.2435339e+00  9.8832475e-01 -5.0829033e-01]
  [ 1.0442554e+02  3.3747453e+00  9.3000176e-01  9.7813226e-01]]

 [[ 8.7072710e+01  3.7434024e+00  7.0642910e-01  3.3307905e-01]
  [ 1.3004913e+02  2.8624891e+00  4.2288377e-01  8.5886900e-01]]

 [[ 1.5960423e+02  2.4293896e+00  9.9398430e-01 -6.1200481e-01]
  [ 1.9619456e+02  2.1266876e+00  9.8481310e-01 -8.7368927e-01]]

 [[ 9.1517370e+01  3.4885337e+00  7.4011109e-01 -2.7807745e-01]
  [ 8.6950066e+01  3.6341171e+00  9.6723817e-01 -8.1374632e-01]]

 [[ 3.9952616e+01  7.7852459e+00  8.8900772e-01  3.1205721e-02]
  [ 8.4667999e+01  4.5515718e+00  8.0668982e-01 -6.4870252e-01]]

 [[ 1.6594898e+02  2.8239944e+00  9.9891880e-01 -9.0132557e-01]
  [ 4.8500279e+01  6.6950799e+00  9.9317601e-01  6.2144435e-01]]

 [[ 3.6503992e+01  6.4359805e+00  8.0707308e-01  2.5633173e-01]
  [ 8.6712016e+

In [24]:
# Speed testing for filter sampling code for 1000 samples with 10 filters each

# Going at it singularly: 361 seconds

# Going at it 5 samples per multiprocessing task: 163 seconds

# Going at it 10 samples per multiprocessing task: 143 seconds

# Going at it 15 samples per multiprocessing task: 143 seconds

# Going at it 20 samples per multiprocessing task: 141 seconds

# Going at it 20 samples per multiprocessing task: 163 seconds

12.53914599092583
13.233824763253162
13.11579265031018
12.963531160246465
12.834575156098758
14.502214021738892
14.404600554404768
12.51261602122208
12.94845273698263
11.061964484892062
10.419007878937599


In [1]:
data_list = [1,2,3,4,5,6,7,8,9,10,11,12,13]
new_list = [data_list[i:i+5] for i in range(0, len(data_list), 5)]
print(new_list)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13]]


In [1]:
import numpy as np

x = np.ones(shape=(4,2,2))
print(x)
y = np.zeros(shape=(2,2,2))
print(y)

x[np.arange(1,3,1)] = y
print(x)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[1. 1.]
  [1. 1.]]]


In [15]:
chunk = 5  # This indexes from 0
chunk_size = 2

x = [[[1,2],[1,2]],[[3,4],[3,4]]]
x = [[[1,2],[1,2]]]
y = np.zeros(shape=(11,2,2))
print(x)
print(y)
start = chunk*chunk_size
end = (chunk+1)*chunk_size
print(start)
print(end)
if end > len(y):
    end = len(y)
print(end)
y[start:end] = np.stack(x)
print(y)

[[[1, 2], [1, 2]]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
10
12
11
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[1. 2.]
  [1. 2.]]]
